"""Add SEO fields to Blog model

Revision ID: 01a8c362808e
Revises: a632855bbdc9
Create Date: 2025-10-03 09:55:24.533581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a8c362808e'
down_revision = 'a632855bbdc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_title', sa.String(length=70), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('focus_keyword', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seo_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seo_grade', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('seo_last_checked', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('seo_last_checked')
        batch_op.drop_column('seo_grade')
        batch_op.drop_column('seo_score')
        batch_op.drop_column('word_count')
        batch_op.drop_column('reading_time')
        batch_op.drop_column('focus_keyword')
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')

    # ### end Alembic commands ###
