"""tạo bảng SEO

Revision ID: 19e507d78166
Revises: 2efebf718a03
Create Date: 2025-10-08 22:28:46.525333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19e507d78166'
down_revision = '2efebf718a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=191),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('group',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_settings_group'))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_settings_group'), ['group'], unique=False)
        batch_op.alter_column('group',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=191),
               existing_nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
