"""Add SEO cache fields to Media

Revision ID: 3f63bb9b27a1
Revises: 4618327f7c7c
Create Date: 2025-10-02 15:37:49.072245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f63bb9b27a1'
down_revision = '4618327f7c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seo_grade', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('seo_last_checked', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('seo_last_checked')
        batch_op.drop_column('seo_grade')
        batch_op.drop_column('seo_score')

    # ### end Alembic commands ###
