"""Add title and updated_at to Media for SEO

Revision ID: 4618327f7c7c
Revises: 3114bf1a6ea6
Create Date: 2025-10-02 14:29:24.644375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4618327f7c7c'
down_revision = '3114bf1a6ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
