"""empty message

Revision ID: 6b0d229d2b45
Revises: 19e507d78166
Create Date: 2025-10-08 23:51:56.733405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0d229d2b45'
down_revision = '19e507d78166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('products_meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('product_meta_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('product_meta_description')
        batch_op.drop_column('products_meta_description')
        batch_op.drop_column('contact_meta_description')
        batch_op.drop_column('about_meta_description')
        batch_op.drop_column('index_meta_description')

    # ### end Alembic commands ###
