"""add is_contact_price to products

Revision ID: 952214066405
Revises: 5c5184cfc65d
Create Date: 2025-10-01 16:12:04.746718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952214066405'
down_revision = '5c5184cfc65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_contact_price', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_contact_price')

    # ### end Alembic commands ###
