"""Add SEO fields to products and blogs

Revision ID: a632855bbdc9
Revises: 3f63bb9b27a1
Create Date: 2025-10-02 19:19:49.372724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a632855bbdc9'
down_revision = '3f63bb9b27a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_alt_text', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_caption', sa.Text(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_alt_text', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_caption', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_caption')
        batch_op.drop_column('image_title')
        batch_op.drop_column('image_alt_text')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('image_caption')
        batch_op.drop_column('image_title')
        batch_op.drop_column('image_alt_text')

    # ### end Alembic commands ###
